#!/usr/bin/env bash
# refresh_yt_cookies.sh — export YouTube cookies từ Chrome, cập nhật .env, redeploy lên AgentBase
# Chạy khi gặp lỗi: "Sign in to confirm you're not a bot"
#
# Usage:
#   ./refresh_yt_cookies.sh            # export cookies + redeploy
#   ./refresh_yt_cookies.sh --cookies-only  # chỉ export cookies, không redeploy
#   ./refresh_yt_cookies.sh --deploy-only   # dùng cookies hiện có, redeploy luôn

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
COOKIES_TMP="/tmp/yt_cookies_$$.txt"
RUNTIME_ID="runtime-1cd83420-bfa0-4784-9702-9f65d713253a"
REGISTRY="vcr.vngcloud.vn/111480-abp111961"
IMAGE_NAME="piano-teacher"
FLAVOR="runtime-s2-general-4x8"
SKILLS_DIR="$SCRIPT_DIR/.claude/skills/agentbase/scripts"

MODE="full"
if [[ "${1:-}" == "--cookies-only" ]]; then MODE="cookies"; fi
if [[ "${1:-}" == "--deploy-only"  ]]; then MODE="deploy";  fi

log()  { echo "▶ $*"; }
ok()   { echo "✅ $*"; }
err()  { echo "❌ $*" >&2; exit 1; }

# ── 1. Export cookies ─────────────────────────────────────────────────────────
if [[ "$MODE" != "deploy" ]]; then
  log "Export YouTube cookies từ Chrome..."

  YT_DLP="$(which yt-dlp 2>/dev/null || echo "")"
  [[ -z "$YT_DLP" ]] && err "yt-dlp không tìm thấy. Cài bằng: pip install yt-dlp"

  "$YT_DLP" \
    --cookies-from-browser chrome \
    --cookies "$COOKIES_TMP" \
    --skip-download --quiet \
    "https://www.youtube.com/watch?v=rq2AQYh0Fqc" 2>/dev/null || true

  [[ ! -f "$COOKIES_TMP" || ! -s "$COOKIES_TMP" ]] && \
    err "Export cookies thất bại. Đảm bảo Chrome đang chạy và đã đăng nhập YouTube."

  LINES=$(wc -l < "$COOKIES_TMP")
  ok "Exported $LINES dòng cookies từ Chrome"

  # Lọc chỉ giữ youtube.com + google.com — giảm từ ~500KB xuống ~30KB
  # Giữ đúng Netscape header, KHÔNG sort (làm hỏng format)
  COOKIES_SLIM="$(mktemp /tmp/yt_cookies_slim_XXXX.txt)"
  {
    echo "# Netscape HTTP Cookie File"
    echo "# This file is generated by yt-dlp.  Do not edit."
    echo ""
    grep -E "^(#HttpOnly_)?([^[:space:]]*\.)?(youtube|google)\.com[[:space:]]" "$COOKIES_TMP"
  } > "$COOKIES_SLIM"
  SLIM_KB=$(( $(wc -c < "$COOKIES_SLIM") / 1024 ))
  ok "Filtered cookies: ${SLIM_KB}KB (từ ${LINES} → $(wc -l < "$COOKIES_SLIM") dòng)"
  rm -f "$COOKIES_TMP"
  COOKIES_TMP="$COOKIES_SLIM"

  # Ghi vào .env (xóa dòng cũ nếu có)
  B64=$(base64 -i "$COOKIES_TMP" | tr -d '\n')
  rm -f "$COOKIES_TMP"

  TMP_ENV=$(mktemp)
  grep -v "^YTDLP_COOKIES_B64" "$ENV_FILE" > "$TMP_ENV" 2>/dev/null || true
  echo "YTDLP_COOKIES_B64=$B64" >> "$TMP_ENV"
  mv "$TMP_ENV" "$ENV_FILE"
  ok ".env cập nhật YTDLP_COOKIES_B64 (${#B64} ký tự)"
fi

[[ "$MODE" == "cookies" ]] && { ok "Chỉ export cookies — xong."; exit 0; }

# ── 2. Docker login ───────────────────────────────────────────────────────────
log "Docker login AgentBase CR..."
bash "$SKILLS_DIR/cr.sh" credentials docker-login > /dev/null 2>&1
ok "Đăng nhập CR thành công"

# ── 3. Build image ────────────────────────────────────────────────────────────
TAG="v$(date +%Y%m%d%H%M%S)"
FULL_IMAGE="$REGISTRY/$IMAGE_NAME:$TAG"
log "Build image $FULL_IMAGE (linux/amd64)..."
docker build --platform linux/amd64 -t "$FULL_IMAGE" "$SCRIPT_DIR" \
  --quiet 2>&1 | tail -1
ok "Build xong: $TAG"

# ── 4. Push image ─────────────────────────────────────────────────────────────
log "Push $FULL_IMAGE..."
docker push "$FULL_IMAGE" 2>&1 | grep -E "digest|Pushed|already" | tail -3
ok "Push xong"

# ── 5. Update runtime ─────────────────────────────────────────────────────────
log "Update AgentBase runtime $RUNTIME_ID..."
bash "$SKILLS_DIR/runtime.sh" update "$RUNTIME_ID" \
  --image "$FULL_IMAGE" \
  --flavor "$FLAVOR" \
  --env-file "$ENV_FILE" \
  --from-cr \
  --network-mode PUBLIC 2>&1 | python3 -c "
import sys, json
d = json.load(sys.stdin)
print(f'  status={d.get(\"status\")}  updated={d.get(\"updatedAt\",\"\")[:19]}')
"
ok "Runtime updated → $TAG"

# ── 6. Health check ───────────────────────────────────────────────────────────
ENDPOINT="https://endpoint-ad747ccf-be75-460a-b997-db20bb823c3a.agentbase-runtime.aiplatform.vngcloud.vn"
log "Health check $ENDPOINT/health ..."
for i in 1 2 3 4 5; do
  HTTP=$(curl -s -o /dev/null -w "%{http_code}" "$ENDPOINT/health" 2>/dev/null || echo "000")
  if [[ "$HTTP" == "200" ]]; then
    ok "Health OK (200)"
    break
  fi
  echo "  [$i] HTTP $HTTP — thử lại sau 5s..."
  sleep 5
done

echo ""
echo "══════════════════════════════════════════════════════"
echo "  Deploy hoàn tất!"
echo "  Image   : $FULL_IMAGE"
echo "  Endpoint: $ENDPOINT"
echo "══════════════════════════════════════════════════════"
